### ISSUE TITLE
Conformal Tracking does not pick up hits from Vertex Barrel Collection

### ISSUE THREAD

**Issue by eleogran** [iLCSoft/ConformalTracking#4]
Running with the nightly build from today, it seems that the CT still does not pick up hits from the VXD Barrel Collection when there are enough in the VXD Endcap.

Output file available here: /afs/cern.ch/work/e/eleogran/public/sitracks_muons.slcio

**Comment by petricm** [comment]
@eleogran I think this is resolved in the last release, can you please verity.

**Comment by dhynds** [comment]
Hi, has this been resolved? I am back in the office on tuesday and we can speak about it...
